[[redirects]]
  from = "/journal/*"
  to = "/blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/legacy/blog/:year/:month/:date/:slug/"
  to = "/blog/:year/:slug/"
  status = 301
  force = true
